[[redirects]]
  from = "/api/*"
  to = "http://geek.itheima.net/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[redirects]]
  from = "/ws/*"
  to = "ws://geek.itheima.net/:splat"
  status = 301
  force = true

